// Copyright 2003-6 Max Howell <max.howell@methylblue.com>
// Redistributable under the terms of the GNU General Public License

#ifndef SETTINGS_DIALOG_H
#define SETTINGS_DIALOG_H

#include "dialog.h" //generated by uic
#include <qtimer.h>


class SettingsDialog : public Dialog
{
Q_OBJECT

public:
  SettingsDialog( QWidget* =0, const char* =0 );

protected:
  virtual void closeEvent( QCloseEvent * );
  virtual void reject();

public slots:
  void addDirectory();
  void removeDirectory();
  void toggleScanAcrossMounts( bool );
  void toggleDontScanRemoteMounts( bool );
  void toggleDontScanRemovableMedia( bool );
  void reset();
  void startTimer();
  void toggleUseAntialiasing( bool = true );
  void toggleVaryLabelFontSizes( bool );
  void changeContrast( int );
  void changeScheme( int );
  void changeMinFontPitch( int );
  void toggleShowSmallFiles( bool );
  void slotSliderReleased();

signals:
  void mapIsInvalid();
  void canvasIsDirty( int );

private:
  QTimer m_timer;

  static const uint TIMEOUT=1000;
};

#endif
